openapi: 3.0.0
info:
  title: Papyrus Logger
  description: Lightweight Node.js Logger
  version: 0.1.9
servers:
  - url: http://localhost:9001/v1/
    description: Local development
  - url: http://api.example.com/v1
    description: Main production server (coming soon)

paths:
  /log:
    get:
      summary: Logs via GET request.
      description: Stores everything found in GET request. Useful to bypass CORS.
      parameters:
        - name: filename
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : string
            minimum: 1
      responses:
        '200':
          description: Successful log
    post:
      summary: Logs via POST request body.
      description: Stores everything found in POST request body.
      responses:
        '200':
          description: Successful log
